---
title: Contact Sheets 
date: 22.11.2020
output:
  html_document:
    keep_html: TRUE
    df_print: paged
  pdf_document: default
---

```{r, include = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "data-contact-sheets/fat80_768x384-",
  out.width = "100%"
)

`%>%` <- purrr::`%>%`

library(tidyverse, warn.conflicts = FALSE)
```

[Using a Retina display](https://support.apple.com/en-us/HT202471),
[dpilove](https://dpi.lv/#27″):

1. 27-inch iMac models introduced in 2014 or later. 
   Native resolution: 5120 x 2880 (16:9) at 218 ppi (pixels per inch).
   Models introduced in 2014 and 2015 support millions of colors,
   and models introduced in 2017 or later support one billion colors.
   Approx. 23 x 13 in.
1. 13-inch MacBook Pro models introduced in late 2012 or later. 
   Native resolution: 2560 x 1600 (16:10) at 227 ppi.
   Support for millions of colors.
   Approx 11 x 7 in.
   

[Taking Control of Plot Scaling](https://www.tidyverse.org/blog/2020/08/taking-control-of-plot-scaling/).

```{r}
# devtools::install_github('r-lib/ragg')
# install.packages("zeallot")

library(ragg)
library(rraysplot)
library(zeallot)
```

iMac.

```{r}
?ragg::agg_jpeg
# ragg::agg_jpeg(width = 3240, height = 1080, res = 218, scaling = 1, quality = 100)
```

MacBook Pro.

```{r}
# ragg::agg_jpeg(file, width = 2160, height = 720, res = 227, scaling = 1, quality = 100)
```

```{r}
file <- "temp.jpeg"
agg_jpeg(file, width = 3240, height = 1080, res = 218, scaling = 1, quality = 100)
plot(sin, -pi, 2*pi)
dev.off()
```


